#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

: ${IMAGE:?"Need to set IMAGE, e.g. gcr.io/coreos-k8s-scale-testing/etcd-operator"}


GIT_SHA=`git rev-parse --short HEAD || echo "GitNotFound"`
cd buildenv/operator
docker build --tag "${IMAGE}" . 1>/dev/null
gcloud docker -a
docker push "${IMAGE}" 1>/dev/null