# Default values for cassandra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  cassandraRepository: gcr.io/cassandra-operator/cassandra-dev
  sidecarRepository: gcr.io/cassandra-operator/cassandra-sidecar-dev
  tag: latest

imagePullPolicy: IfNotPresent

resources:
  limits:
    memory: 8Gi
  requests:
    memory: 8Gi
dataVolumeClaim:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi

#Example authentication for AWS S3 based backups
#env:
#  - name: AWS_ACCESS_KEY_ID
#    valueFrom:
#      secretKeyRef:
#        name: awsbackuptest
#        key: access
#  - name: AWS_SECRET_ACCESS_KEY
#    valueFrom:
#      secretKeyRef:
#        name: awsbackuptest
#        key: secret
#  - name: AWS_REGION
#    value: "us-west-2"

#Example authentication for AWS GCP based backups
env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: "/tmp/user-config/service_key.json"
  - name: GOOGLE_CLOUD_PROJECT
    value: "cassandra-operator"
  - name: BUCKET_NAME
    value: "ben-cassandra-operator"

userConfigMapVolumeSource:
  name: gcp-auth-reference
  items:
    - key: service_key.json
      path:  service_key.json

# Example GCP ConfigMap
#apiVersion: extensions/v1beta1
#kind: ConfigMap
#metadata:
#  name: gcp-auth-reference
#data:
#  service_key.json: "XXXXXXXXX"



#restoreFromBackup: backup-hostname

prometheusEnabled: false